# Generated by Django 3.1.4 on 2020-12-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201216_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
    ]
