# Generated by Django 3.1.4 on 2020-12-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_yourmom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourMom',
        ),
    ]
